# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
# Color Scheme
foreground #FFFFFF
background #1e1e2e

# Cursor
cursor #45475a
cursor_text_color #45475a
# disable titlebar
# §hide_window_decorations yes


# Added by Gogh
include colors.conf
