version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'blue'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}blue{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .UserName }}'
    foreground = 'yellow'
    background = '#29315A'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Path }}'
    foreground = 'green'
    background = '#29315A'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ .HEAD }}'
    foreground = 'blue'
    background = '#29315A'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    foreground = '#154de7'
    background = '#29315A'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#7FD5EA'
    background = '#29315A'
    type = 'go'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
    foreground = '#42E66C'
    background = '#29315A'
    type = 'node'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'ruby'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'java'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#9B6BDF'
    background = '#29315A'
    type = 'julia'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}'
    foreground = '#9B6BDF'
    background = '#29315A'
    type = 'battery'
    style = 'diamond'
    foreground_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
      charged_icon = ' '
      charging_icon = '⇡ '
      discharging_icon = '⇣ '

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .FormattedMs }}'
    foreground = 'lightYellow'
    background = '#29315A'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'
      threshold = 150

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '❯'
    foreground = 'blue'
    background = '#29315A'
    type = 'text'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
